### ISSUE TITLE
BugFix for admin profile

### ISSUE THREAD

**Issue by SabriKorkmaz** [ossarioglu/SWE574-SWEet_Dewarriors#128]
Admin has no profile object.
It should be fixed at backend.

**Comment by SabriKorkmaz** [comment]
@ossarioglu can you give more detail ?

**Comment by ossarioglu** [comment]
Bug is fixed by adding a control method. It's triggered when profile related service is called. Control method checks whether there is a profile object related to user or not.
This fixed all externally created user-profile missing issues (not only admin)
