### ISSUE TITLE
Pinterest Research for UI Design

### ISSUE THREAD

**Issue by betty-gures** [ossarioglu/SWE574-SWEet_Dewarriors#19]
Pinterest Research for UI Design is done in the following steps:

- [x] Create a mural board 
- [x] Gather good examples 
- [x] Decide on color scheme
- [x] Select useful UI elements

**Comment by betty-gures** [comment]
Mural link that anyone can edit:
https://app.mural.co/invitation/mural/fatmabetul9285/1647016493067?sender=u7fae40229a29e96b0ebf9107&key=d80bf4f5-557f-409d-b2c3-47b762e28410

**Comment by ossarioglu** [comment]
Task will be transformed into mock-up designs
