### ISSUE TITLE
Decide on a name for our project

### ISSUE THREAD

**Issue by SabriKorkmaz** [ossarioglu/SWE574-SWEet_Dewarriors#30]

**Comment by betty-gures** [comment]
Some ideas: Time-share, Share Care, Sublime Time, Equality Quality, Social Share, Timeology, **Sharity** (share+charity)

A helpful tool to generate name ideas: https://www.name-generator.org.uk/

**Comment by sahar-avsh** [comment]
**Timeopolis**

**Comment by ossarioglu** [comment]
I like Sharity, my vote is on this.

I can add **Sharify** **SocializeUs** as an alternatives

**Comment by betty-gures** [comment]
**Sharity** is decided as the name of the project
