### ISSUE TITLE
Mockup Design

### ISSUE THREAD

**Issue by sahar-avsh** [ossarioglu/SWE574-SWEet_Dewarriors#36]
Finish mockup designs for :

- [x] **Landing** page

- [x] **Home** page

- [x] **Log-in**

- [x] **Profile**

- [x] **Offer look**    

- [x] **Time line**

- [x] **Calendar** page  

- [x] **Notification** page  

- [x] **Searching** page

- [x] **Admin** profile  

- [x] **Rate & Review** profile

**Comment by sahar-avsh** [comment]
**Notification page** had been successfully designed

**Comment by sahar-avsh** [comment]
**Search page** had been successfully designed

**Comment by sahar-avsh** [comment]
**Profile page** had been successfully designed

**Comment by sahar-avsh** [comment]
**Offer look** had been successfully designed

**Comment by betty-gures** [comment]
**Home page** had been successfully designed

**Comment by sahar-avsh** [comment]
**Rate & Review page** had been successfully designed

**Comment by sahar-avsh** [comment]
**Inbox page** had been successfully designed

**Comment by betty-gures** [comment]
**Landing Page** had been successfully designed

**Comment by sahar-avsh** [comment]
**Admin Page** had been successfully designed
